apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python-k8s
  namespace: dev
  labels:
    app: app-python-k8s
    env: dev
    version: 1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python-k8s
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: app-python-k8s
    spec:
      containers:
      - name: app-python
        image: ludsilva/app-python-distroless:1.1
        ports:
        - containerPort: 5000
          name: "app-port"
        resources:
          limits:
            memory: "64Mi"
            cpu: "50m"
          requests:
            memory: "32Mi"
            cpu: "25m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3