apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: dev
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
     metadata:
       labels:
         app: redis
     spec:
       containers:
       - image: redis
         name: redis
         ports:
         - containerPort: 6379
         resources:
           requests:
             memory: "64Mi"
             cpu: "100m"
           limits:
             memory: "128Mi"
             cpu: "500m"