apiVersion: v1
kind: Service
metadata:
  name: app-python-k8s-svc
  namespace: dev
spec:
  selector:
    app: app-python-k8s
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30080
  type: NodePort