apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          ports:
            - containerPort: {{ .Values.app.service.targetPort }}
              name: "app-port"
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.app.probes.path }}
              port: {{ .Values.app.service.targetPort }}
            initialDelaySeconds: {{ .Values.app.probes.initialDelaySeconds }}
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: {{ .Values.app.probes.path }}
              port: {{ .Values.app.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3