app:
  replicaCount: 3
  image:
    repository: ludsilva/app-python-distroless
    tag: "1.4"
  namespace: dev
  service:
    type: NodePort
    port: 80
    targetPort: 5000
    nodePort: 30080
  resources:
    limits:
      memory: "64Mi"
      cpu: "50m"
    requests:
      memory: "32Mi"
      cpu: "25m"
  probes: 
    path: /health
    initialDelaySeconds: 15

redis:
  image: "redis"
  replicas: 1
  port: 6379
  service:
    type: "ClusterIP"
    port: 6379
    targetPort: 6379
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "500m"